### ISSUE TITLE
Schemas for data and Responses for APIs

### ISSUE THREAD

**Issue by sarbikbetal** [codeiiest-dev/codeiiest-web#1]
@codeiiest-dev/backend
Guys please add the schemas for our database models and add the API endpoints with vague descriptions here, I'll add them to Swagger properly and link it up here.
I've added some examples for your reference. Add your own here.

#### API
**User**
`/login`
User will login with username and password
`/update`
Update user info.

**Posts**
`/new`
Create a new post

#### Schema
**user**
```javascript
{
  username: String,
  password: String,
  dob: Date
}
```

**Comment by sarbikbetal** [comment]
@raydwaipayan add label Documentation

**Comment by raydwaipayan** [comment]
The endpoints will be as follows:
/api/user/signup -> create an user
/api/user/signin  -> login
/api/user/forgotpassword -> reset usee
/api/user/handle/* -> add/modify social handles

For the db, the users and handlesmigrations can be referred to.
