### ISSUE TITLE
[BUG] Events in arbitrary order

### ISSUE THREAD

**Issue by hrahul2605** [codeiiest-dev/codeiiest-web#32]
Currently the events are not sorted on the event timeline as seen from the screenshot below. 
Events should be sorted in increasing order with respect to `startDate`.

![image](https://user-images.githubusercontent.com/48245702/125913749-ba2e1cc0-a0c9-4e3c-a596-d99343d1ae2e.png)

**Comment by hrahul2605** [comment]
Method to be fixed 
https://github.com/codeiiest-dev/codeiiest-web/blob/7a7c8e60d2bbacfd667c2853692fe2a69a59bdbe/src/logic/events.ts#L6

**Comment by raushnn** [comment]
In line 9 >> items.sort((a, b) => (dayjs(a).isAfter(dayjs(b)) ? 1 : -1)))
