### ISSUE TITLE
[ NEW ] addition of ISSUE TEMPLATE 

### ISSUE THREAD

**Issue by NeerajHazarika** [codeiiest-dev/codeiiest-web#34]
## ISSUE TEMPLATES

With issue forms, you can create issue templates that have customizable web form fields. You can encourage contributors to include specific, structured information by using issue forms in your repository.

**Here's a sample version of issue form**

![sample-issue-form](https://user-images.githubusercontent.com/72177954/126118262-d648daeb-49d3-4034-a7f4-17e74890b1ee.png)

**Comment by arnabsen1729** [comment]
- Remove the contact details field.
- Version doesn't make any sense for the website tho. 
- Make browser's field required.
- Code of Conduct is not needed to file issues (at least in this repo).

**Comment by NeerajHazarika** [comment]
okay got it, will make the required changes and make a PR

**Comment by NeerajHazarika** [comment]
From which branch should i make PR ? [deault branch](https://github.com/NeerajHazarika/codeiiest-web/tree/v2) or [new branch](https://github.com/NeerajHazarika/codeiiest-web/tree/iss34) both have same code so ig it doesnt matter 🤔

This is the [PR](https://github.com/NeerajHazarika/codeiiest-web/pull/2) that i made on my own repo

**Comment by hrahul2605** [comment]
From the new branch make PR to the v2 branch @NeerajHazarika
