### ISSUE TITLE
Create a JSON file 

### ISSUE THREAD

**Issue by arnabsen1729** [codeiiest-dev/codeiiest-web#7]
The JSON file will have data of 
- [ ] Current Core members
- [ ] People in managerial positions
- [ ] Alumni
```js
{
   name: ' '
   batch: ' '
   desig: [ ]
   chapters: [ ]
   social_handles: {}
}
```

For details on how to collect these data contact the admins

**Comment by sadn1ck** [comment]
For details, refer to : https://codeiiest.github.io/
